name: Bump version
on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tag name'
        required: true
        default: '0.0.1'
        type: string
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tagname }}