name: Scratch Desktop Download and Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: wget
      run: |
        mkdir output
        pwd
        cd output
        ls -lh
        url_dst="https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe"
        url_dst=`curl -L --HEAD ${url_dst} -w %{url_effective} | tail -n 1`
        echo $url_dst
        wget -nv "$url_dst"
        ls -lh ..
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: "output/*Setup.exe"
        
