name: Scratch Desktop Download and Release
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: wget
      run: |
        mkdir output
        pwd
        cd output
        ls -lh
        url_dst="https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe"
        url_dst=`curl -L --HEAD ${url_dst} -w %{url_effective} | tail -n 1`
        echo $url_dst
        wget -nv "$url_dst"
        ls -lh
